spring:
  application:
    name: security-service

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
